name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          cache: maven
          java-version: '25'
          distribution: temurin
          server-id: central
          server-username: CENTRAL_TOKEN_USERNAME
          server-password: CENTRAL_TOKEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build & publish
        run: set -o pipefail && mvn -P release --batch-mode clean deploy -pl '!raven-example' | tee maven-deploy.log
        env:
          CENTRAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Bump version
        run: |
          OLD=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD"
          NEW="$MAJOR.$MINOR.$((PATCH + 1))"
          mvn versions:set -DnewVersion=$NEW -DgenerateBackupPoms=false -DprocessAllModules=true
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump version to $NEW"
          git push

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: maven-logs
          path: maven-deploy.log
